name: PGTap Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli
      - name: Supabase Start
        run: supabase start
      - name: install pg_prove
        run: sudo cpan TAP::Parser::SourceHandler::pgTAP
        env:
          SHELL: /bin/bash
      - name: Run Tests
        run: pg_prove -d supabase -U postgres -h localhost -p 5432 -f supabase/tests/*.sql